version: '3'
services:
  mysql-user-service:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: NexChangeUserDB
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: 111111
    ports:
      - "3307:3306"
    networks:
      - backend

  zookeeper-service:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka-service:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-service
    networks:
      - backend

  redis-service:
    image: redis:5
    ports:
      - "6379:6379"
    networks:
      - backend

  nexchange-userservice:
    build: .
    environment:
      - DB_HOST=mysql-user-service
      - DB_NAME=NexChangeUserDB
      - DB_USER=user
      - MYSQL_PASSWORD=111111
      - REDIS_HOST=redis-service
      - KAFKA_SERVERS=kafka-service:9092
      - JWT_SECRET=jwt_token
    depends_on:
      - mysql-user-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
