version: '3'
services:
  mysql-user-service:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: NexChangeUserDB
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: password
    container_name: mysql-user-service
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper-service:
    image: wurstmeister/zookeeper
    container_name: zookeeper-service
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka-service:
    image: wurstmeister/kafka
    container_name: kafka-service
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-service
    networks:
      - backend

  redis-service:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend


  nexchange-userservice:
    build: .
    environment:
      - DB_HOST=mysql-user-service
      - DB_NAME=NexChangeUserDB
      - DB_USER=user
      - MYSQL_PASSWORD=password
      - REDIS_HOST=redis-service
      - KAFKA_SERVERS=kafka-service:9092
      - JWT_SECRET=jwt_token
    depends_on:
      mysql-user-service:
        condition: service_healthy
    networks:
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  backend:
    driver: bridge
