services:
  redis:
    image: "redis:latest"
    container_name: "redis-server"
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis-data:/data

networks:
  redis-network:
    driver: bridge

volumes:
  redis-data:

