apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  MYSQL_HOST: "mysql-user-service"
  MYSQL_PORT: "3306"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"

