apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: ['sh', '-c', 'until nc -z zookeeper-service 2181; do echo waiting for zookeeper; sleep 2; done;']
        - name: create-kafka-dirs
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /mnt/data/kafka/kafka-logs
              chown -R 1000:1000 /mnt/data/kafka
          volumeMounts:
            - name: kafka-storage
              mountPath: /mnt/data/kafka
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.13-2.8.1
          ports:
            - containerPort: 9092
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            # 修改监听器配置
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"
            # 删除 INTERNAL 相关配置
            # - name: KAFKA_INTER_BROKER_LISTENER_NAME
            #   value: "INTERNAL"
            # ZooKeeper配置
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "60000"
            - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "60000"
            # Topic配置
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "10485760"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "10485760"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            # 添加一些重要的配置
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            # 功能开关
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
            - name: KAFKA_AUTO_LEADER_REBALANCE_ENABLE
              value: "true"
            # 日志配置
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "168"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "1073741824"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          volumeMounts:
            - name: kafka-storage
              mountPath: /kafka
            - name: kafka-storage
              mountPath: /kafka/kafka-logs
              subPath: kafka-logs
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: kafka-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka