apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9092
          env:
            # 动态分配 KAFKA_BROKER_ID
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name  # StatefulSet的Pod name包含index，可以作为broker id
            # Zookeeper 服务地址
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            # 配置 Kafka 的监听地址
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            # 配置 Kafka 的广告地址，确保每个 Kafka 实例可以通过集群 DNS 被其他组件访问
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka-headless.$(POD_NAMESPACE).svc.cluster.local:9092"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None  # 无需单个 IP，允许 Pod 通过域名进行通信
  selector:
    app: kafka
  ports:
    - port: 9092
      name: kafka

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka
