apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
        - name: wait-for-zookeeper
          image: busybox
          command: ['sh', '-c', 'until nc -z zookeeper-service 2181; do echo waiting for zookeeper; sleep 2; done;']
      containers:
        - name: kafka
          image: wurstmeister/kafka:2.13-2.8.1
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://$(POD_IP):9092"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            # Zookeeper 连接设置
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "60000"
            - name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "60000"
            # 重试设置
            - name: KAFKA_RETRY_BACKOFF_MS
              value: "500"
            - name: KAFKA_RECONNECT_BACKOFF_MS
              value: "1000"
            - name: KAFKA_RECONNECT_BACKOFF_MAX_MS
              value: "10000"

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-headless
#spec:
#  clusterIP: None  # 无需单个 IP，允许 Pod 通过域名进行通信
#  selector:
#    app: kafka
#  ports:
#    - port: 9092
#      name: kafka

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: kafka-service
#spec:
#  type: ClusterIP
#  selector:
#    app: kafka
#  ports:
#    - port: 9092
#      targetPort: 9092
#      name: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kafka