apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-user-service
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: "NexChangeUserDB"
            - name: MYSQL_USER
              value: “root”
          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-user-service
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306