apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root-password: YWRtaW4=  # 'admin' encoded
  user-password: dXNlcg==  # 'user' encoded
  jwt-secret: and0LXRva2Vu # 'jwt-token' encoded