apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:latest
          ports:
            - containerPort: 2181
          env:
            # 添加环境变量来重置状态
            - name: ZOO_STANDALONE_ENABLED
              value: "true"
            - name: ZOO_4LW_COMMANDS_WHITELIST
              value: "*"
            - name: ZOO_AUTOPURGE_PURGEINTERVAL
              value: "1"
            - name: ZOO_AUTOPURGE_SNAPRETAINCOUNT
              value: "3"
          volumeMounts:
          - name: zookeeper-data
            mountPath: /var/lib/zookeeper/data
            subPath: data
          - name: zookeeper-data
            mountPath: /var/lib/zookeeper/datalog
            subPath: datalog
          - name: zookeeper-data
            mountPath: /var/lib/zookeeper/logs
            subPath: logs
      volumes:
            - name: zookeeper-data
              persistentVolumeClaim:
                claimName: zookeeper-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  ports:
    - port: 2181
  selector:
    app: zookeeper
