apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:3.7.0
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: data
              mountPath: /data
            - name: log
              mountPath: /datalog
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zookeeper-pvc
        - name: log
          persistentVolumeClaim:
            claimName: zookeeper-log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
