spring:
  config:
#    import: "file:./src/main/resources/secret.properties"
    import: "optional:classpath:secret.properties"
  datasource:
    url: jdbc:mysql://localhost:3306/NexChangeUserDB
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: ${JWT_SECRET}
server:
  port: 8081

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG